// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-agent/internal/model"
)

func newSPictureBookCategory(db *gorm.DB, opts ...gen.DOOption) sPictureBookCategory {
	_sPictureBookCategory := sPictureBookCategory{}

	_sPictureBookCategory.sPictureBookCategoryDo.UseDB(db, opts...)
	_sPictureBookCategory.sPictureBookCategoryDo.UseModel(&model.SPictureBookCategory{})

	tableName := _sPictureBookCategory.sPictureBookCategoryDo.TableName()
	_sPictureBookCategory.ALL = field.NewAsterisk(tableName)
	_sPictureBookCategory.Id = field.NewUint64(tableName, "id")
	_sPictureBookCategory.CategoryId = field.NewString(tableName, "category_id")
	_sPictureBookCategory.CategoryName = field.NewString(tableName, "category_name")
	_sPictureBookCategory.Sort = field.NewInt(tableName, "sort")
	_sPictureBookCategory.Type = field.NewInt(tableName, "type")
	_sPictureBookCategory.Status = field.NewString(tableName, "status")
	_sPictureBookCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_sPictureBookCategory.UpdatedAt = field.NewTime(tableName, "updated_at")

	_sPictureBookCategory.fillFieldMap()

	return _sPictureBookCategory
}

type sPictureBookCategory struct {
	sPictureBookCategoryDo

	ALL          field.Asterisk
	Id           field.Uint64 // 主键id
	CategoryId   field.String // 栏目ID
	CategoryName field.String // 栏目名称
	Sort         field.Int    // 排序,倒序
	Type         field.Int    // 1中文绘本,2英文绘本,3古诗绘本,4英语词汇
	Status       field.String // 状态,on启用,off禁用
	CreatedAt    field.Time   // 添加时间
	UpdatedAt    field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (s sPictureBookCategory) Table(newTableName string) *sPictureBookCategory {
	s.sPictureBookCategoryDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sPictureBookCategory) As(alias string) *sPictureBookCategory {
	s.sPictureBookCategoryDo.DO = *(s.sPictureBookCategoryDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sPictureBookCategory) updateTableName(table string) *sPictureBookCategory {
	s.ALL = field.NewAsterisk(table)
	s.Id = field.NewUint64(table, "id")
	s.CategoryId = field.NewString(table, "category_id")
	s.CategoryName = field.NewString(table, "category_name")
	s.Sort = field.NewInt(table, "sort")
	s.Type = field.NewInt(table, "type")
	s.Status = field.NewString(table, "status")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *sPictureBookCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sPictureBookCategory) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.Id
	s.fieldMap["category_id"] = s.CategoryId
	s.fieldMap["category_name"] = s.CategoryName
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["type"] = s.Type
	s.fieldMap["status"] = s.Status
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s sPictureBookCategory) clone(db *gorm.DB) sPictureBookCategory {
	s.sPictureBookCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sPictureBookCategory) replaceDB(db *gorm.DB) sPictureBookCategory {
	s.sPictureBookCategoryDo.ReplaceDB(db)
	return s
}

type sPictureBookCategoryDo struct{ gen.DO }

type ISPictureBookCategoryDo interface {
	gen.SubQuery
	Debug() ISPictureBookCategoryDo
	WithContext(ctx context.Context) ISPictureBookCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISPictureBookCategoryDo
	WriteDB() ISPictureBookCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISPictureBookCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISPictureBookCategoryDo
	Not(conds ...gen.Condition) ISPictureBookCategoryDo
	Or(conds ...gen.Condition) ISPictureBookCategoryDo
	Select(conds ...field.Expr) ISPictureBookCategoryDo
	Where(conds ...gen.Condition) ISPictureBookCategoryDo
	Order(conds ...field.Expr) ISPictureBookCategoryDo
	Distinct(cols ...field.Expr) ISPictureBookCategoryDo
	Omit(cols ...field.Expr) ISPictureBookCategoryDo
	Join(table schema.Tabler, on ...field.Expr) ISPictureBookCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISPictureBookCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISPictureBookCategoryDo
	Group(cols ...field.Expr) ISPictureBookCategoryDo
	Having(conds ...gen.Condition) ISPictureBookCategoryDo
	Limit(limit int) ISPictureBookCategoryDo
	Offset(offset int) ISPictureBookCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISPictureBookCategoryDo
	Unscoped() ISPictureBookCategoryDo
	Create(values ...*model.SPictureBookCategory) error
	CreateInBatches(values []*model.SPictureBookCategory, batchSize int) error
	Save(values ...*model.SPictureBookCategory) error
	First() (*model.SPictureBookCategory, error)
	Take() (*model.SPictureBookCategory, error)
	Last() (*model.SPictureBookCategory, error)
	Find() ([]*model.SPictureBookCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SPictureBookCategory, err error)
	FindInBatches(result *[]*model.SPictureBookCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SPictureBookCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISPictureBookCategoryDo
	Assign(attrs ...field.AssignExpr) ISPictureBookCategoryDo
	Joins(fields ...field.RelationField) ISPictureBookCategoryDo
	Preload(fields ...field.RelationField) ISPictureBookCategoryDo
	FirstOrInit() (*model.SPictureBookCategory, error)
	FirstOrCreate() (*model.SPictureBookCategory, error)
	FindByPage(offset int, limit int) (result []*model.SPictureBookCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISPictureBookCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sPictureBookCategoryDo) Debug() ISPictureBookCategoryDo {
	return s.withDO(s.DO.Debug())
}

func (s sPictureBookCategoryDo) WithContext(ctx context.Context) ISPictureBookCategoryDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sPictureBookCategoryDo) ReadDB() ISPictureBookCategoryDo {
	return s.Clauses(dbresolver.Read)
}

func (s sPictureBookCategoryDo) WriteDB() ISPictureBookCategoryDo {
	return s.Clauses(dbresolver.Write)
}

func (s sPictureBookCategoryDo) Session(config *gorm.Session) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Session(config))
}

func (s sPictureBookCategoryDo) Clauses(conds ...clause.Expression) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sPictureBookCategoryDo) Returning(value interface{}, columns ...string) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sPictureBookCategoryDo) Not(conds ...gen.Condition) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sPictureBookCategoryDo) Or(conds ...gen.Condition) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sPictureBookCategoryDo) Select(conds ...field.Expr) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sPictureBookCategoryDo) Where(conds ...gen.Condition) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sPictureBookCategoryDo) Order(conds ...field.Expr) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sPictureBookCategoryDo) Distinct(cols ...field.Expr) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sPictureBookCategoryDo) Omit(cols ...field.Expr) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sPictureBookCategoryDo) Join(table schema.Tabler, on ...field.Expr) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sPictureBookCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISPictureBookCategoryDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sPictureBookCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) ISPictureBookCategoryDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sPictureBookCategoryDo) Group(cols ...field.Expr) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sPictureBookCategoryDo) Having(conds ...gen.Condition) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sPictureBookCategoryDo) Limit(limit int) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sPictureBookCategoryDo) Offset(offset int) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sPictureBookCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sPictureBookCategoryDo) Unscoped() ISPictureBookCategoryDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sPictureBookCategoryDo) Create(values ...*model.SPictureBookCategory) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sPictureBookCategoryDo) CreateInBatches(values []*model.SPictureBookCategory, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sPictureBookCategoryDo) Save(values ...*model.SPictureBookCategory) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sPictureBookCategoryDo) First() (*model.SPictureBookCategory, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBookCategory), nil
	}
}

func (s sPictureBookCategoryDo) Take() (*model.SPictureBookCategory, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBookCategory), nil
	}
}

func (s sPictureBookCategoryDo) Last() (*model.SPictureBookCategory, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBookCategory), nil
	}
}

func (s sPictureBookCategoryDo) Find() ([]*model.SPictureBookCategory, error) {
	result, err := s.DO.Find()
	return result.([]*model.SPictureBookCategory), err
}

func (s sPictureBookCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SPictureBookCategory, err error) {
	buf := make([]*model.SPictureBookCategory, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sPictureBookCategoryDo) FindInBatches(result *[]*model.SPictureBookCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sPictureBookCategoryDo) Attrs(attrs ...field.AssignExpr) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sPictureBookCategoryDo) Assign(attrs ...field.AssignExpr) ISPictureBookCategoryDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sPictureBookCategoryDo) Joins(fields ...field.RelationField) ISPictureBookCategoryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sPictureBookCategoryDo) Preload(fields ...field.RelationField) ISPictureBookCategoryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sPictureBookCategoryDo) FirstOrInit() (*model.SPictureBookCategory, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBookCategory), nil
	}
}

func (s sPictureBookCategoryDo) FirstOrCreate() (*model.SPictureBookCategory, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBookCategory), nil
	}
}

func (s sPictureBookCategoryDo) FindByPage(offset int, limit int) (result []*model.SPictureBookCategory, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sPictureBookCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sPictureBookCategoryDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sPictureBookCategoryDo) Delete(models ...*model.SPictureBookCategory) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sPictureBookCategoryDo) withDO(do gen.Dao) *sPictureBookCategoryDo {
	s.DO = *do.(*gen.DO)
	return s
}
