// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-agent/internal/model"
)

func newSPictureBookItem(db *gorm.DB, opts ...gen.DOOption) sPictureBookItem {
	_sPictureBookItem := sPictureBookItem{}

	_sPictureBookItem.sPictureBookItemDo.UseDB(db, opts...)
	_sPictureBookItem.sPictureBookItemDo.UseModel(&model.SPictureBookItem{})

	tableName := _sPictureBookItem.sPictureBookItemDo.TableName()
	_sPictureBookItem.ALL = field.NewAsterisk(tableName)
	_sPictureBookItem.Id = field.NewUint64(tableName, "id")
	_sPictureBookItem.BookId = field.NewString(tableName, "book_id")
	_sPictureBookItem.Pic = field.NewString(tableName, "pic")
	_sPictureBookItem.BPic = field.NewString(tableName, "b_pic")
	_sPictureBookItem.Audio = field.NewString(tableName, "audio")
	_sPictureBookItem.Position = field.NewInt(tableName, "position")
	_sPictureBookItem.Content = field.NewString(tableName, "content")
	_sPictureBookItem.Status = field.NewString(tableName, "status")
	_sPictureBookItem.CreatedAt = field.NewTime(tableName, "created_at")
	_sPictureBookItem.UpdatedAt = field.NewTime(tableName, "updated_at")

	_sPictureBookItem.fillFieldMap()

	return _sPictureBookItem
}

type sPictureBookItem struct {
	sPictureBookItemDo

	ALL       field.Asterisk
	Id        field.Uint64 // 主键id
	BookId    field.String // 绘本id
	Pic       field.String // 绘本详情图
	BPic      field.String // 绘本详情大图
	Audio     field.String // 绘本详音频
	Position  field.Int    // 排序位置
	Content   field.String // 内容
	Status    field.String // 状态,on启用,off禁用
	CreatedAt field.Time   // 添加时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (s sPictureBookItem) Table(newTableName string) *sPictureBookItem {
	s.sPictureBookItemDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sPictureBookItem) As(alias string) *sPictureBookItem {
	s.sPictureBookItemDo.DO = *(s.sPictureBookItemDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sPictureBookItem) updateTableName(table string) *sPictureBookItem {
	s.ALL = field.NewAsterisk(table)
	s.Id = field.NewUint64(table, "id")
	s.BookId = field.NewString(table, "book_id")
	s.Pic = field.NewString(table, "pic")
	s.BPic = field.NewString(table, "b_pic")
	s.Audio = field.NewString(table, "audio")
	s.Position = field.NewInt(table, "position")
	s.Content = field.NewString(table, "content")
	s.Status = field.NewString(table, "status")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *sPictureBookItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sPictureBookItem) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.Id
	s.fieldMap["book_id"] = s.BookId
	s.fieldMap["pic"] = s.Pic
	s.fieldMap["b_pic"] = s.BPic
	s.fieldMap["audio"] = s.Audio
	s.fieldMap["position"] = s.Position
	s.fieldMap["content"] = s.Content
	s.fieldMap["status"] = s.Status
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s sPictureBookItem) clone(db *gorm.DB) sPictureBookItem {
	s.sPictureBookItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sPictureBookItem) replaceDB(db *gorm.DB) sPictureBookItem {
	s.sPictureBookItemDo.ReplaceDB(db)
	return s
}

type sPictureBookItemDo struct{ gen.DO }

type ISPictureBookItemDo interface {
	gen.SubQuery
	Debug() ISPictureBookItemDo
	WithContext(ctx context.Context) ISPictureBookItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISPictureBookItemDo
	WriteDB() ISPictureBookItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISPictureBookItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISPictureBookItemDo
	Not(conds ...gen.Condition) ISPictureBookItemDo
	Or(conds ...gen.Condition) ISPictureBookItemDo
	Select(conds ...field.Expr) ISPictureBookItemDo
	Where(conds ...gen.Condition) ISPictureBookItemDo
	Order(conds ...field.Expr) ISPictureBookItemDo
	Distinct(cols ...field.Expr) ISPictureBookItemDo
	Omit(cols ...field.Expr) ISPictureBookItemDo
	Join(table schema.Tabler, on ...field.Expr) ISPictureBookItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISPictureBookItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISPictureBookItemDo
	Group(cols ...field.Expr) ISPictureBookItemDo
	Having(conds ...gen.Condition) ISPictureBookItemDo
	Limit(limit int) ISPictureBookItemDo
	Offset(offset int) ISPictureBookItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISPictureBookItemDo
	Unscoped() ISPictureBookItemDo
	Create(values ...*model.SPictureBookItem) error
	CreateInBatches(values []*model.SPictureBookItem, batchSize int) error
	Save(values ...*model.SPictureBookItem) error
	First() (*model.SPictureBookItem, error)
	Take() (*model.SPictureBookItem, error)
	Last() (*model.SPictureBookItem, error)
	Find() ([]*model.SPictureBookItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SPictureBookItem, err error)
	FindInBatches(result *[]*model.SPictureBookItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SPictureBookItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISPictureBookItemDo
	Assign(attrs ...field.AssignExpr) ISPictureBookItemDo
	Joins(fields ...field.RelationField) ISPictureBookItemDo
	Preload(fields ...field.RelationField) ISPictureBookItemDo
	FirstOrInit() (*model.SPictureBookItem, error)
	FirstOrCreate() (*model.SPictureBookItem, error)
	FindByPage(offset int, limit int) (result []*model.SPictureBookItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISPictureBookItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sPictureBookItemDo) Debug() ISPictureBookItemDo {
	return s.withDO(s.DO.Debug())
}

func (s sPictureBookItemDo) WithContext(ctx context.Context) ISPictureBookItemDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sPictureBookItemDo) ReadDB() ISPictureBookItemDo {
	return s.Clauses(dbresolver.Read)
}

func (s sPictureBookItemDo) WriteDB() ISPictureBookItemDo {
	return s.Clauses(dbresolver.Write)
}

func (s sPictureBookItemDo) Session(config *gorm.Session) ISPictureBookItemDo {
	return s.withDO(s.DO.Session(config))
}

func (s sPictureBookItemDo) Clauses(conds ...clause.Expression) ISPictureBookItemDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sPictureBookItemDo) Returning(value interface{}, columns ...string) ISPictureBookItemDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sPictureBookItemDo) Not(conds ...gen.Condition) ISPictureBookItemDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sPictureBookItemDo) Or(conds ...gen.Condition) ISPictureBookItemDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sPictureBookItemDo) Select(conds ...field.Expr) ISPictureBookItemDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sPictureBookItemDo) Where(conds ...gen.Condition) ISPictureBookItemDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sPictureBookItemDo) Order(conds ...field.Expr) ISPictureBookItemDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sPictureBookItemDo) Distinct(cols ...field.Expr) ISPictureBookItemDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sPictureBookItemDo) Omit(cols ...field.Expr) ISPictureBookItemDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sPictureBookItemDo) Join(table schema.Tabler, on ...field.Expr) ISPictureBookItemDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sPictureBookItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISPictureBookItemDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sPictureBookItemDo) RightJoin(table schema.Tabler, on ...field.Expr) ISPictureBookItemDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sPictureBookItemDo) Group(cols ...field.Expr) ISPictureBookItemDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sPictureBookItemDo) Having(conds ...gen.Condition) ISPictureBookItemDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sPictureBookItemDo) Limit(limit int) ISPictureBookItemDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sPictureBookItemDo) Offset(offset int) ISPictureBookItemDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sPictureBookItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISPictureBookItemDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sPictureBookItemDo) Unscoped() ISPictureBookItemDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sPictureBookItemDo) Create(values ...*model.SPictureBookItem) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sPictureBookItemDo) CreateInBatches(values []*model.SPictureBookItem, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sPictureBookItemDo) Save(values ...*model.SPictureBookItem) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sPictureBookItemDo) First() (*model.SPictureBookItem, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBookItem), nil
	}
}

func (s sPictureBookItemDo) Take() (*model.SPictureBookItem, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBookItem), nil
	}
}

func (s sPictureBookItemDo) Last() (*model.SPictureBookItem, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBookItem), nil
	}
}

func (s sPictureBookItemDo) Find() ([]*model.SPictureBookItem, error) {
	result, err := s.DO.Find()
	return result.([]*model.SPictureBookItem), err
}

func (s sPictureBookItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SPictureBookItem, err error) {
	buf := make([]*model.SPictureBookItem, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sPictureBookItemDo) FindInBatches(result *[]*model.SPictureBookItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sPictureBookItemDo) Attrs(attrs ...field.AssignExpr) ISPictureBookItemDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sPictureBookItemDo) Assign(attrs ...field.AssignExpr) ISPictureBookItemDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sPictureBookItemDo) Joins(fields ...field.RelationField) ISPictureBookItemDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sPictureBookItemDo) Preload(fields ...field.RelationField) ISPictureBookItemDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sPictureBookItemDo) FirstOrInit() (*model.SPictureBookItem, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBookItem), nil
	}
}

func (s sPictureBookItemDo) FirstOrCreate() (*model.SPictureBookItem, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBookItem), nil
	}
}

func (s sPictureBookItemDo) FindByPage(offset int, limit int) (result []*model.SPictureBookItem, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sPictureBookItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sPictureBookItemDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sPictureBookItemDo) Delete(models ...*model.SPictureBookItem) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sPictureBookItemDo) withDO(do gen.Dao) *sPictureBookItemDo {
	s.DO = *do.(*gen.DO)
	return s
}
